### ISSUE TITLE
[ts] Cannot find module 'react-3d-viewer'.

### ISSUE THREAD

**Issue by jhk115** [dwqdaiwenqi/react-3d-viewer#1]
Any idea how to resolve this? I am using webpack and it can't seem to locate this module.

**Comment by dwqdaiwenqi** [comment]
The problem has been fixed. Thank u

**Comment by dwqdaiwenqi** [comment]
The problem has been fixed. Thank u

**Comment by jhk115** [comment]
Thanks!
