### ISSUE TITLE
Dae file texture problem

### ISSUE THREAD

**Issue by LucasGomes9** [dwqdaiwenqi/react-3d-viewer#16]
I can see the model, but for some reason the texture don't show

![image](https://user-images.githubusercontent.com/26194427/78063237-46ce3900-7366-11ea-9e9c-92b98cfb723c.png)

Code:
![image](https://user-images.githubusercontent.com/26194427/78063953-5f8b1e80-7367-11ea-9473-44d96ef57552.png)

**Comment by chquiej** [comment]
Do you fix this problem?

**Comment by LucasGomes9** [comment]
Yeap, the "problem" was in the model. I needed to open the 3D Max project and change textures path... My textures where at ./src/assets. So i changed the texture path in the model using 3D Max to '/src/assets' and worked
